// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Candidate struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Dob        string `json:"dob"`
	Policy     string `json:"policy"`
	BioLink    string `json:"bioLink"`
	VotedCount int    `json:"votedCount"`
	ImageURL   string `json:"imageURL"`
}

type CandidateVoteUpdated struct {
	ID         string `json:"id"`
	VotedCount int    `json:"votedCount"`
}
